### ISSUE TITLE
Support Placeholder for SQL

### ISSUE THREAD

**Issue by tank-pooja** [sqlfluff/sqlfluff#1871]
## Expected Behaviour
It should support generic SQL Queries.

We are using a query like : 

SELECT  * FROM users WHERE id = ?;

## Observed Behaviour

Showing Error:  Found unparsable section

## Dialect
Postgres

Include your SQLFluff configuration here
```
[sqlfluff]
dialect=postgres

**Comment by barrywhart** [comment]
Is the use of `?` a feature of Postgres itself? A client library? Something else?

**Comment by barrywhart** [comment]
Changed from "bug" to "enhancement" because I'm pretty sure this is not standard Postgres behavior. Rather, it is part of a client library or similar. So this sounds like a request to add a new (albeit simple) templater, not an enhancement to the Postgres dialect.

In fact, `?` is a built-in Postgres operator for working with JSON data. Sometimes this usage collides with the use of `?` as described here, e.g.:
* https://stackoverflow.com/questions/38370972/how-do-i-use-postgresql-jsonb-operators-containing-a-question-mark-via-jdb
* https://github.com/metabase/metabase/issues/1964

**Comment by tank-pooja** [comment]
@barrywhart , Thank you for your reply.
Yes, We are using this client library of Go - https://github.com/jmoiron/sqlx. So, is that possible to have support for `$variable` or `:variable` ?

**Comment by barrywhart** [comment]
It's possible. As I mentioned above, I think we'd treat this as a new templater. I think it's similar to #1216.

**Comment by barrywhart** [comment]
I think this is addressed by #1887. Can you confirm, @tank-pooja?

**Comment by tank-pooja** [comment]
@barrywhart , Yes, that's working. But, it's failing for this :

`L:   7 | P:  15 | L048 | Missing whitespace before '5'`

Here is config

```
[sqlfluff]
dialect= postgres
templater = sqlalchemy
[sqlfluff:templater:sqlalchemy:context]
id='5' 
```

And Query
```
SELECT
    *
FROM public.users
WHERE id = :id;

```

**Comment by tank-pooja** [comment]
@jacopofar , thank you for adding support for a different variable placeholder.

@barrywhart , But, I am still facing issues as mentioned above, regarding whitespace.

**Comment by jacopofar** [comment]
I can reproduce it, I thought the templater was adding whitespaces but I don't see any, and the automated tests are checking for an exact match, so I don't know where's the issue originating.
