### ISSUE TITLE
Parsing error while using ALTER commands on Snowflake Objects

### ISSUE THREAD

**Issue by arumugam-pounraj** [sqlfluff/sqlfluff#3479]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

Getting parsing error while trying to parse SQL statements which uses ALTER commands.

Tried parsing below ALTER statements with SQLFLUFF and got parsing error. The statements are from Snowflake docs
```
ALTER ACCOUNT SET TIMEZONE = 'UTC';
ALTER DATABASE DB_TEST RENAME TO DB_TEST_NEW;
ALTER RESOURCE MONITOR RM_TEST SET CREDIT_QUOTA=2000 TRIGGERS ON 80 PERCENT DO NOTIFY ON 100 PERCENT DO SUSPEND_IMMEDIATE;
ALTER STORAGE INTEGRATION TEST_MYINT SET ENABLED = TRUE;
ALTER NETWORK POLICY MYPOLICY1 SET ALLOWED_IP_LIST=('192.168.1.0/24', '192.168.255.100');
ALTER ROLE ROLE1 RENAME TO ROLE2;
ALTER SHARE SALES_S ADD ACCOUNTS = AB12345;
ALTER FILE FORMAT MY_FORMAT SET FIELD_DELIMITER = ',';
ALTER SEQUENCE SEQ_TEST SET INCREMENT = 2;
ALTER PIPE MYPIPE SET PIPE_EXECUTION_PAUSED = TRUE;
ALTER PROCEDURE IF EXISTS PROCEDURE1(float) RENAME TO PROCEDURE2;
ALTER MASKING POLICY EMAIL_MASK SET BODY ->
  CASE
    WHEN CURRENT_ROLE() IN ('ANALYST') THEN VAL
    ELSE SHA2(VAL, 512)
  END;
```

```
Error Output
L:  31 | P:   1 |  PRS | Line 31, Position 1: Found unparsable section: "ALTER ACCOUNT SET TIMEZONE = 'UTC'"
L:  32 | P:   1 |  PRS | Line 32, Position 1: Found unparsable section: 'ALTER DATABASE DB_TEST RENAME TO DB_TEST...'
L:  34 | P:   1 |  PRS | Line 34, Position 1: Found unparsable section: 'ALTER RESOURCE MONITOR RM_TEST SET CREDI...'
L:  35 | P:   1 |  PRS | Line 35, Position 1: Found unparsable section: 'ALTER STORAGE INTEGRATION TEST_MYINT SET...'
L:  36 | P:   1 |  PRS | Line 36, Position 1: Found unparsable section: 'ALTER NETWORK POLICY MYPOLICY1 SET ALLOW...'
L:  38 | P:   1 |  PRS | Line 38, Position 1: Found unparsable section: 'ALTER ROLE ROLE1 RENAME TO ROLE2'
L:  40 | P:   1 |  PRS | Line 40, Position 1: Found unparsable section: 'ALTER SHARE SALES_S ADD ACCOUNTS = AB123...'
L:  11 | P:   1 |  PRS | Line 11, Position 1: Found unparsable section: 'ALTER FILE FORMAT MY_FORMAT SET FIELD_DE...'
L:  41 | P:   1 |  PRS | Line 41, Position 1: Found unparsable section: 'ALTER SEQUENCE MYSEQ SET INCREMENT = 2'
L:  49 | P:   1 |  PRS | Line 49, Position 1: Found unparsable section: 'ALTER PIPE MYPIPE SET PIPE_EXECUTION_PAU...'
L:  50 | P:   1 |  PRS | Line 50, Position 1: Found unparsable section: 'ALTER PROCEDURE IF EXISTS PROCEDURE1(flo...'
L:  52 | P:   1 |  PRS | Line 52, Position 1: Found unparsable section: 'ALTER MASKING POLICY EMAIL_MASK SET BODY...'
```

### Expected Behaviour

The Statements which are mentioned above are valid statements and executed fine in the Snowflake UI without any issues

### Observed Behaviour

Could see the ALTER commands are failing for some of the Snowflake objects. For other objects like Schema, Table, View etc the ALTER commands were working fine

### How to reproduce

1. Place all the ALTER statements mentioned above in a Alter_test.sql file
2. Execute below command
`sqlfluff lint  Alter_test.sql --dialect snowflake`

### Dialect

Snowflake

### Version

0.13.2

### Configuration

[sqlfluff]
dialect = snowflake

[sqlfluff:rules:L014]
extended_capitalisation_policy = consistent

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by jared-rimmer** [comment]
Hi, I'm attempting to have a go at this as my first contribution via adding `ALTER ACCOUNT`

I was wondering if I could get some help with how to implement[ all the different params that are available](https://docs.snowflake.com/en/sql-reference/sql/alter-account)?

I've started off with this syntax:
```

    _account_params = OneOf(
        Sequence("ALLOW_ID_TOKEN", Ref("EqualsSegment"), Ref("BooleanLiteralGrammar")),
        Sequence("CLIENT_ENCRYPTION_KEY_SIZE", Ref("EqualsSegment"), Ref("IntegerSegment")),
        Sequence("ENFORCE_SESSION_POLICY", Ref("EqualsSegment"), Ref("BooleanLiteralGrammar")),
        Sequence("EXTERNAL_OAUTH_ADD_PRIVILEGED_ROLES_TO_BLOCKED_LIST", Ref("EqualsSegment"), Ref("BooleanLiteralGrammar")),
        Sequence("INITIAL_REPLICATION_SIZE_LIMIT_IN_TB", Ref("EqualsSegment"), Ref("IntegerSegment")),

    )
```
Then using it in this way within the `match_grammar` block:

```
        OneOf(
            _account_params,
           ...
)
```

Just wondering if this makes sense and /or is the most efficient way of implementing it.

Thanks!

**Comment by WittierDinosaur** [comment]
Hey @jared-rimmer , that seems liek a reasonable approach. The best bet is to open a PR, and one of the maintainers will add suggestions there

**Comment by nevdelap** [comment]
I was about to open a similar issue, but three of the statements look like they could be the same thing. This may help you test this issue's fixes, or let me know if any of them should be their own separate issue. :pray: 

```
ALTER WAREHOUSE CI_TRANSFORMING
SET
    COMMENT = 'Warehouse for dbt development transformations in CI'
    , AUTO_RESUME = TRUE
    , AUTO_SUSPEND=30;

CREATE RESOURCE MONITOR DEV_TRANSFORMING
WITH
    CREDIT_QUOTA = 3  -- 3 credits per day, half of what it used to be.
    FREQUENCY = DAILY
    START_TIMESTAMP = IMMEDIATELY
    NOTIFY_USERS = (NEVD)  -- email must be verified.
    TRIGGERS
        ON 85 PERCENT DO NOTIFY
        ON 100 PERCENT DO SUSPEND_IMMEDIATE;

ALTER RESOURCE MONITOR DEV_TRANSFORMING
SET NOTIFY_USERS = (NEVD);

CREATE RESOURCE MONITOR CI_TRANSFORMING
WITH
    CREDIT_QUOTA = 3  -- 3 credits per day, given the other half.
    FREQUENCY = DAILY
    START_TIMESTAMP = IMMEDIATELY
    NOTIFY_USERS = (NEVD)
    TRIGGERS
        ON 85 PERCENT DO NOTIFY
        ON 100 PERCENT DO SUSPEND_IMMEDIATE;

ALTER RESOURCE MONITOR CI_TRANSFORMING
SET NOTIFY_USERS = (NEVD);
```

results in...

```
> docker run -it --rm -v $PWD:/sql sqlfluff/sqlfluff:2.1.0 lint --dialect snowflake sql/repro.sql                                          (snowflake)
== [sql/repro.sql] FAIL
L:   3 | P:   1 | LT02 | Line should not be indented.
                       | [layout.indent]
L:   3 | P:  68 |  PRS | Line 3, Position 68: Found unparsable section: '\n    ,
                       | AUTO_RESUME = TRUE\n    , AUTO_SUS...'
L:   8 | P:   5 |  PRS | Line 8, Position 5: Found unparsable section: '\n
                       | CREDIT_QUOTA = 3  -- 3 credits per ...'
L:  17 | P:   1 |  PRS | Line 17, Position 1: Found unparsable section: 'ALTER
                       | RESOURCE MONITOR DEV_TRANSFORMING\n...'
L:  21 | P:   5 |  PRS | Line 21, Position 5: Found unparsable section: '\n
                       | CREDIT_QUOTA = 3  -- 3 credits per ...'
L:  30 | P:   1 |  PRS | Line 30, Position 1: Found unparsable section: 'ALTER
                       | RESOURCE MONITOR CI_TRANSFORMING\nS...'
WARNING: Parsing errors found and dialect is set to 'snowflake'. Have you configured your dialect correctly?
All Finished 📜 🎉!
>

with an empty `.sqlfluff`.
```

**Comment by Orangemic** [comment]
Hi, I am running into a similar issue whereby all ALTER WAREHOUSE queries are producing PRS errors. These are examples of queries I'm trying to run:

```SQL ALTER WAREHOUSE WH_TEST WAREHOUSE_TYPE = 'STANDARD';
  ALTER WAREHOUSE WH_TEST SET AUTO_SUSPEND = 600;
  ALTER WAREHOUSE WH_TEST SET AUTO_RESUME = FALSE;
  ALTER WAREHOUSE WH_TEST SET MIN_CLUSTER_COUNT = 1;
  ALTER WAREHOUSE WH_TEST SET MAX_CLUSTER_COUNT = 1;
  ALTER WAREHOUSE WH_TEST SET SCALING_POLICY = 'ECONOMY';
```

Now I'm new here, so I want to know if someone is already working on this feature? 
Or can I contribute by adding these statements somewhere? Thanks in advance!

**Comment by Kylea650** [comment]
> I'm also facing parse errors when creating a STORAGE INTEGRATION like this:
> 
> ```
> CREATE OR REPLACE STORAGE INTEGRATION whatever
> TYPE = EXTERNAL_STAGE
> ENABLED = TRUE
> STORAGE_PROVIDER = 'S3'
> STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::we:role/whatever'
> STORAGE_ALLOWED_LOCATIONS = ('s3://whatever/');
> ```
> 
> The parsing violation is:
> 
> ```
> ==== parsing violations ====
> L:   9 | P:  15 |  PRS | Line 9, Position 15: Found unparsable section: "\nSTORAGE_PROVIDER
>                        | = 'S3'\nSTORAGE_AWS_ROL..."
> WARNING: Parsing errors found and dialect is set to 'snowflake'. Have you configured your dialect correctly?
> ```
> 
> I understand that this is not support and I might try to contribute, is that right?

This should be solved be #5236. sqlfluff previously expected the storage_provider to be unquoted e.g. S3 instead of 'S3'.

**Comment by moreaupascal56** [comment]
> Hi, I am running into a similar issue whereby all ALTER WAREHOUSE queries are producing PRS errors. These are examples of queries I'm trying to run:
> 
> ```sql
>   ALTER WAREHOUSE WH_TEST SET AUTO_SUSPEND = 600;
>   ALTER WAREHOUSE WH_TEST SET AUTO_RESUME = FALSE;
>   ALTER WAREHOUSE WH_TEST SET MIN_CLUSTER_COUNT = 1;
>   ALTER WAREHOUSE WH_TEST SET MAX_CLUSTER_COUNT = 1;
>   ALTER WAREHOUSE WH_TEST SET SCALING_POLICY = 'ECONOMY';
> ```
> 
> Now I'm new here, so I want to know if someone is already working on this feature? Or can I contribute by adding these statements somewhere? Thanks in advance!

Hello, these **Alter warehouse** queries have been fixed by !5264

**Comment by moreaupascal56** [comment]
Hello there, I tested all the queries that have been mentioned in this issue to be able to work more easily on this issue. 
The queries that are still failing are the ones below: 

```sql

-- warehouse
-- Here i think the issue are the commas
ALTER WAREHOUSE CI_TRANSFORMING
SET COMMENT = 'Warehouse for dbt development transformations in CI'
    , AUTO_RESUME = TRUE
    , AUTO_SUSPEND=30;


--Resource monitor
CREATE RESOURCE MONITOR DEV_TRANSFORMING
WITH
    CREDIT_QUOTA = 3  -- 3 credits per day, half of what it used to be.
    FREQUENCY = DAILY
    START_TIMESTAMP = IMMEDIATELY
    NOTIFY_USERS = (NEVD)  -- email must be verified.
    TRIGGERS
        ON 85 PERCENT DO NOTIFY
        ON 100 PERCENT DO SUSPEND_IMMEDIATE;

ALTER RESOURCE MONITOR DEV_TRANSFORMING
SET NOTIFY_USERS = (NEVD);

CREATE RESOURCE MONITOR CI_TRANSFORMING
WITH
    CREDIT_QUOTA = 3  -- 3 credits per day, given the other half.
    FREQUENCY = DAILY
    START_TIMESTAMP = IMMEDIATELY
    NOTIFY_USERS = (NEVD)
    TRIGGERS
        ON 85 PERCENT DO NOTIFY
        ON 100 PERCENT DO SUSPEND_IMMEDIATE;

ALTER RESOURCE MONITOR CI_TRANSFORMING
SET NOTIFY_USERS = (NEVD);

ALTER RESOURCE MONITOR RM_TEST SET CREDIT_QUOTA=2000 TRIGGERS ON 80 PERCENT DO NOTIFY ON 100 PERCENT DO SUSPEND_IMMEDIATE;



-- Account
ALTER ACCOUNT SET TIMEZONE = 'UTC';

-- Database
ALTER DATABASE DB_TEST RENAME TO DB_TEST_NEW;

-- Network policy
ALTER NETWORK POLICY MYPOLICY1 SET ALLOWED_IP_LIST=('192.168.1.0/24', '192.168.255.100');

-- sequence
ALTER SEQUENCE SEQ_TEST SET INCREMENT = 2;

--procedure
ALTER PROCEDURE IF EXISTS PROCEDURE1(float) RENAME TO PROCEDURE2;

-- MASKING POLICY
ALTER MASKING POLICY EMAIL_MASK SET BODY ->
  CASE
    WHEN CURRENT_ROLE() IN ('ANALYST') THEN VAL
    ELSE SHA2(VAL, 512)
  END;
```


I think we could open one PR per resource type, because it will be easier to develop and review. If anyone wants to contribute on one sub-part of this issue feel free to just comment that you are handling one resource type and let's do it :D 
We can monitor the progress here: 

- [ ] Warehouse
- [ ] Resource monitor
- [ ] Account
- [ ] Database
- [ ] Network policy
- [ ] Sequence
- [ ] Procedure
- [ ] Masking policy

PS: If anyone is motivated enough to create distinct issues per resource type that would be better but I think we can work with this issue like I said above. Btw it is easier to have issues related to one problem (so one resource type for example)

**Comment by moreaupascal56** [comment]
warehouse part done in https://github.com/sqlfluff/sqlfluff/pull/5268

**Comment by WittierDinosaur** [comment]
I think this issue is now complete. All of it parses on main. Thanks everyone for contributing to this anthology issue!
