### ISSUE TITLE
Error parsing JSON on dbt templater, sqlfluff v.1.4.5 and on main branch

### ISSUE THREAD

**Issue by nhrebinka** [sqlfluff/sqlfluff#4189]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

I installed `sqlfluff` v.1.4.5 and tried running the following command
`diff-quality --violations sqlfluff --compare-branch origin/dev`
It returned the following output:
```
> diff-quality --violations sqlfluff --compare-branch origin/dev
sqlfluff lint --format=json macros/dbt_artifacts/upload_tests.sql
Error parsing JSON output (Extra data: line 1 column 3 (char 2)): '19:36:04  Unable to do partial parsing because config vars, config profile, or config target have changed\r\n[]\r\n'
Traceback (most recent call last):
  File "C:\Users\w500239\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\w500239\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\w500239\AppData\Local\Programs\Python\Python38\Scripts\diff-quality.exe\__main__.py", line 7, in <module>
  File "C:\Users\w500239\AppData\Local\Programs\Python\Python38\lib\site-packages\diff_cover\diff_quality_tool.py", line 349, in main
    percent_passing = generate_quality_report(
  File "C:\Users\w500239\AppData\Local\Programs\Python\Python38\lib\site-packages\diff_cover\diff_quality_tool.py", line 279, in generate_quality_report
    reporter.generate_report(output_file)
  File "C:\Users\w500239\AppData\Local\Programs\Python\Python38\lib\site-packages\diff_cover\report_generator.py", line 280, in generate_report
    report = template.render(self._context())
  File "C:\Users\w500239\AppData\Local\Programs\Python\Python38\lib\site-packages\diff_cover\report_generator.py", line 329, in _context
    context = super().report_dict()
  File "C:\Users\w500239\AppData\Local\Programs\Python\Python38\lib\site-packages\diff_cover\report_generator.py", line 201, in report_dict
    src_stats = {src: self._src_path_stats(src) for src in self.src_paths()}
  File "C:\Users\w500239\AppData\Local\Programs\Python\Python38\lib\site-packages\diff_cover\report_generator.py", line 84, in src_paths
    for src, summary in self._diff_violations().items()
  File "C:\Users\w500239\AppData\Local\Programs\Python\Python38\lib\site-packages\diff_cover\report_generator.py", line 178, in _diff_violations
    violations = self._violations.violations_batch(
  File "C:\Users\w500239\AppData\Local\Programs\Python\Python38\lib\site-packages\sqlfluff\diff_quality_plugin.py", line 64, in violations_batch
    report = json.loads(o)
  File "C:\Users\w500239\AppData\Local\Programs\Python\Python38\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "C:\Users\w500239\AppData\Local\Programs\Python\Python38\lib\json\decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 3 (char 2)
```
when I ran sqlfluff directly, like this `sqlfluff lint macros/dbt_artifacts/upload_tests.sql` it works as expected

Also tried the above on `main` branch of sqlfluff and got the same results

### Expected Behaviour

Expected it to work without error

### Observed Behaviour

works fine as `sqlfluff lint xxx`, gives an error on `diff-quality`

### How to reproduce

1. pip install git+https://github.com/sqlfluff/sqlfluff.git@main
2. diff-quality --violations sqlfluff --compare-branch origin/dev

### Dialect

dbt

### Version

PS C:\Users\w500239\lakefront-us> sqlfluff --version
sqlfluff, version 1.4.5
PS C:\Users\w500239\lakefront-us> diff-cover --version
diff-cover 7.3.0

and tried also on `main` branch of `sqlfluff`

### Configuration

I dont think it is relevant. Including the first section of `.sqlfluff`
```
[sqlfluff]
verbose = 0
nocolor = False
dialect = snowflake
templater = dbt
rules = None
exclude_rules = L034,L029,L025,L031,L054,L044
recurse = 0
# Very large files can make the parser effectively hang.
# The more efficient check is the _byte_ limit check which
# is enabled by default. The previous _character_ limit check
# is still present for backward compatibility. This will be
# removed in a future version.
# Set either to 0 to disable.
large_file_skip_char_limit = 0
large_file_skip_byte_limit = 30000
output_line_length = 80
runaway_limit = 10
ignore_templated_areas = True
encoding = autodetect
disable_noqa = False
# Comma separated list of file extensions to lint.
# NB: This config will only apply in the root folder.
sql_file_exts = .sql,.sql.j2,.dml,.ddl
# CPU processes to use while linting.
# If positive, just implies number of processes.
# If negative or zero, implies number_of_cpus - specified_number.
# e.g. -1 means use all processors but one. 0  means all cpus.
processes = 0
```

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by barrywhart** [comment]
@nhrebinka: I have a PR (#4190) which I think fixes this. Are you willing to test it? 🙏

**Comment by nhrebinka** [comment]
@barrywhart it is fixed in your PR! Thank you! Here is the full log:
```
> pip install git+https://github.com/barrywhart/sqlfluff.git@bhart-issue_4189_diff_quality_error_parsing_json
Collecting git+https://github.com/barrywhart/sqlfluff.git@bhart-issue_4189_diff_quality_error_parsing_json
  Cloning https://github.com/barrywhart/sqlfluff.git (to revision bhart-issue_4189_diff_quality_error_parsing_json) to c:\users\w500239\appdata\local\temp\pip-req-build-7wkd9r1m
  Running command git clone --filter=blob:none --quiet https://github.com/barrywhart/sqlfluff.git 'C:\Users\w500239\AppData\Local\Temp\pip-req-build-7wkd9r1m'
  Running command git checkout -b bhart-issue_4189_diff_quality_error_parsing_json --track origin/bhart-issue_4189_diff_quality_error_parsing_json
  Branch 'bhart-issue_4189_diff_quality_error_parsing_json' set up to track remote branch 'bhart-issue_4189_diff_quality_error_parsing_json' from 'origin'.
  Switched to a new branch 'bhart-issue_4189_diff_quality_error_parsing_json'
  Resolved https://github.com/barrywhart/sqlfluff.git to commit 135bd9bad4df31e7fc53d2408e3d9f737c0e5079
  Preparing metadata (setup.py) ... done
Requirement already satisfied: appdirs in c:\users\w500239\appdata\local\programs\python\python38\lib\site-packages (from sqlfluff==1.4.5) (1.4.4)
Requirement already satisfied: chardet in c:\users\w500239\appdata\local\programs\python\python38\lib\site-packages (from sqlfluff==1.4.5) (3.0.4)
Requirement already satisfied: click in c:\users\w500239\appdata\local\programs\python\python38\lib\site-packages (from sqlfluff==1.4.5) (8.0.3)
Requirement already satisfied: colorama>=0.3 in c:\users\w500239\appdata\local\programs\python\python38\lib\site-packages (from sqlfluff==1.4.5) (0.4.3)
Requirement already satisfied: diff-cover>=2.5.0 in c:\users\w500239\appdata\local\programs\python\python38\lib\site-packages (from sqlfluff==1.4.5) (7.3.0)
Requirement already satisfied: Jinja2 in c:\users\w500239\appdata\local\programs\python\python38\lib\site-packages (from sqlfluff==1.4.5) (3.1.2)
Requirement already satisfied: pathspec in c:\users\w500239\appdata\local\programs\python\python38\lib\site-packages (from sqlfluff==1.4.5) (0.9.0)
Requirement already satisfied: pydantic in c:\users\w500239\appdata\local\programs\python\python38\lib\site-packages (from sqlfluff==1.4.5) (1.10.2)
Requirement already satisfied: pytest in c:\users\w500239\appdata\local\programs\python\python38\lib\site-packages (from sqlfluff==1.4.5) (6.2.5)
Requirement already satisfied: pyyaml>=5.1 in c:\users\w500239\appdata\local\programs\python\python38\lib\site-packages (from sqlfluff==1.4.5) (6.0)
Requirement already satisfied: regex in c:\users\w500239\appdata\local\programs\python\python38\lib\site-packages (from sqlfluff==1.4.5) (2022.10.31)
Requirement already satisfied: rich in c:\users\w500239\appdata\local\programs\python\python38\lib\site-packages (from sqlfluff==1.4.5) (12.6.0)
Requirement already satisfied: ruamel.yaml in c:\users\w500239\appdata\local\programs\python\python38\lib\site-packages (from sqlfluff==1.4.5) (0.17.21)
Requirement already satisfied: tblib in c:\users\w500239\appdata\local\programs\python\python38\lib\site-packages (from sqlfluff==1.4.5) (1.7.0)
Requirement already satisfied: toml in c:\users\w500239\appdata\local\programs\python\python38\lib\site-packages (from sqlfluff==1.4.5) (0.10.2)
Requirement already satisfied: tqdm in c:\users\w500239\appdata\local\programs\python\python38\lib\site-packages (from sqlfluff==1.4.5) (4.62.3)
Requirement already satisfied: typing_extensions in c:\users\w500239\appdata\local\programs\python\python38\lib\site-packages (from sqlfluff==1.4.5) (4.4.0)
Requirement already satisfied: Pygments<3.0.0,>=2.9.0 in c:\users\w500239\appdata\local\programs\python\python38\lib\site-packages (from diff-cover>=2.5.0->sqlfluff==1.4.5) (2.9.0)
Requirement already satisfied: pluggy<2,>=0.13.1 in c:\users\w500239\appdata\local\programs\python\python38\lib\site-packages (from diff-cover>=2.5.0->sqlfluff==1.4.5) (1.0.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\w500239\appdata\local\programs\python\python38\lib\site-packages (from Jinja2->sqlfluff==1.4.5) (2.0.1)
Requirement already satisfied: atomicwrites>=1.0 in c:\users\w500239\appdata\local\programs\python\python38\lib\site-packages (from pytest->sqlfluff==1.4.5) (1.4.0)
Requirement already satisfied: py>=1.8.2 in c:\users\w500239\appdata\local\programs\python\python38\lib\site-packages (from pytest->sqlfluff==1.4.5) (1.10.0)
Requirement already satisfied: iniconfig in c:\users\w500239\appdata\local\programs\python\python38\lib\site-packages (from pytest->sqlfluff==1.4.5) (1.1.1)
Requirement already satisfied: attrs>=19.2.0 in c:\users\w500239\appdata\local\programs\python\python38\lib\site-packages (from pytest->sqlfluff==1.4.5) (20.3.0)
Requirement already satisfied: packaging in c:\users\w500239\appdata\local\programs\python\python38\lib\site-packages (from pytest->sqlfluff==1.4.5) (20.9)
Requirement already satisfied: commonmark<0.10.0,>=0.9.0 in c:\users\w500239\appdata\local\programs\python\python38\lib\site-packages (from rich->sqlfluff==1.4.5) (0.9.1)
Requirement already satisfied: ruamel.yaml.clib>=0.2.6 in c:\users\w500239\appdata\local\programs\python\python38\lib\site-packages (from ruamel.yaml->sqlfluff==1.4.5) (0.2.7)
Requirement already satisfied: pyparsing>=2.0.2 in c:\users\w500239\appdata\local\programs\python\python38\lib\site-packages (from packaging->pytest->sqlfluff==1.4.5) (2.4.7)
PS C:\Users\w500239\lakefront-us> diff-quality --violations sqlfluff --compare-branch origin/dev
sqlfluff lint --format=json macros/dbt_artifacts/upload_tests.sql
-------------
Diff Quality
Quality Report: ['C:\\Users\\w500239\\AppData\\Local\\Programs\\Python\\Python38\\python.exe', '-m', 'sqlfluff.cli.commands']
Diff: origin/dev...HEAD, staged and unstaged changes
-------------
macros/dbt_artifacts/upload_tests.sql (100%)
-------------
Total:   30 lines
Violations: 0 lines
% Quality: 100%
-------------
```

**Comment by Jay-code0** [comment]
Hi, Im still getting this exact issue in
SQLfluff 1.4.5, diff-cover 7.5.0 and dbt templater 1.4.5

**Comment by wcmbishop** [comment]
I am seeing the same issue with sqlfluff-templater-dbt version 3.0.2. It seems to be intermittent, and I'm not sure what scenario causes it.
