### ISSUE TITLE
dbt `1.7.14` breaks with `ImportError: cannot import name 'read_user_config' from 'dbt.config'`

### ISSUE THREAD

**Issue by elyobo** [sqlfluff/sqlfluff#5841]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

`dbt-core` has just released `1.7.14`; installing `dbt-core` `1.7.14`, `dbt-bigquery` `1.7.7` and the latest `sqlfluff` `3.0.5` and `sqlfluff-templater-dbt` `3.0.5` then trying to lint results in `ImportError: cannot import name 'read_user_config' from 'dbt.config'`

All else the same but using `dbt-core` `1.7.13` linting works

Probably relevant, dbt-core 1.7.14 release notes - https://github.com/dbt-labs/dbt-core/releases/tag/v1.7.14
https://github.com/dbt-labs/dbt-core/issues/9183 is mentioned and sounds like it might be relevant

### Expected Behaviour

linting should work without errors

### Observed Behaviour

linting tails with `ImportError: cannot import name 'read_user_config' from 'dbt.config'`

### How to reproduce

install `dbt-core` `1.7.14`, `dbt-bigquery` `1.7.7`, `sqlfluff` `3.0.5`, and `sqlfluff-templater-dbt` `3.0.5`
run `sqlfluff lint`

### Dialect

bigquery

### Version

 `dbt-core` `1.7.14`, `dbt-bigquery` `1.7.7`, `sqlfluff` `3.0.5`, and `sqlfluff-templater-dbt` `3.0.5`

```
python --version
Python 3.12.1
```

```
poetry run sqlfluff --version
sqlfluff, version 3.0.5
```

### Configuration

probably not relevant

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by jtcohen6** [comment]
@elyobo Thanks for opening the issue!

It would have been this change, which we backported to v1.7.14 + v1.6.14 in order to provide users with a proactive deprecation warning and ability to adopt a more explicit inheritance order for materializations:
- https://github.com/dbt-labs/dbt-core/pull/9998
- https://github.com/dbt-labs/dbt-core/pull/10008

In quick summary: `dbt.config.project.read_project_flags` is replacing `dbt.config.profile.read_user_config`. Neither of these methods is documented or stable as part of dbt's Python API.

It looks like `read_user_config` isn't actually being used for dbt >= 1.5, so I think this could be fixed just by moving the import down beneath the `else` conditional. (Also, dbt-core versions before v1.6 are no longer officially supported.)

https://github.com/sqlfluff/sqlfluff/blob/baceed9907908e055b79ca50ce6203bcd7949f39/plugins/sqlfluff-templater-dbt/sqlfluff_templater_dbt/templater.py#L148-L166

```python
        from dbt.config.runtime import RuntimeConfig as DbtRuntimeConfig
        ...

        if self.dbt_version_tuple >= (1, 5):
            ...
        else:
            ...      
            from dbt.config import read_user_config
            user_config = read_user_config(flags.PROFILES_DIR)
```

**Comment by anshjain18** [comment]
I haven't done any version upgrade on either dbt-core or sqlfluff, but still started facing this exact issue suddenly in the past 3-4 days. My versions are:
1. dbt-core = 1.6.14
2. sqlfluff = 2.3.0

What can be the possible reasons behind this and how to solve the same?

**Comment by anshjain18** [comment]
@greg-finley I think the issue is that the new version where this bug is fixed hasn't been published yet.
The latest version, 3.0.5 was released 2 weeks ago which doesn't seem like it has the fix included

**Comment by yingqiaozheng** [comment]
With the dbt-core=1.7.1 the same issue still happening. Anybody has any update? Thank you.

**Comment by greg-finley** [comment]
Hello @yingqiaozheng did you try sqlfluff 3.0.6 (released last week)? It should be fixed via https://github.com/sqlfluff/sqlfluff/pull/5842

**Comment by derik-roby** [comment]
Unfortunately, I still face this issue with sqlfluff 3.0.6 and dbt-postgres 1.8

**Comment by ZZNK** [comment]
stil experiencing this with sqlfluff 3.0.7 and

dbt-core==1.7.10 \
dbt-postgres==1.7.10 \
dbt-redshift==1.7.4 \
dbt-snowflake==1.7.2 \
dbt-bigquery==1.7.6

**Comment by reubster** [comment]
> stil experiencing this with sqlfluff 3.0.7 and
> 
> dbt-core==1.7.10 dbt-postgres==1.7.10 dbt-redshift==1.7.4 dbt-snowflake==1.7.2 dbt-bigquery==1.7.6

@ZZNK - this was resolved for me by forcing an upgrade of sqlfluff-templater-dbt to 3.0.7 also

**Comment by CarMoreno** [comment]
Thanks @reubster , I had to update sqlfluff to 3.0.7 and all works. I am using dbt 1.8.1

```
dbt-core==1.8.1
dbt-postgres==1.8.1
sqlfluff==3.0.7
sqlfluff-templater-dbt==3.0.7
```
